obiba/mica2

mica-search/src/main/java/org/obiba/mica/search/JoinQueryExecutor.java, mica-search/src/main/java/org/obiba/mica/search/rest/EsQueryResultParser.java, mica-web-model/src/main/protobuf/MicaSearch.proto
changed required fields in StatsAggregationResultDataDto to optional
=> fix variable/study search result for variables with no related studies

mica-core/src/main/java/org/obiba/mica/config/AggregationsConfiguration.java, mica-core/src/main/java/org/obiba/mica/micaConfig/AggregationInfo.java, mica-core/src/main/java/org/obiba/mica/micaConfig/AggregationsConfig.java, mica-core/src/main/java/org/obiba/mica/micaConfig/MicaConfig.java, mica-core/src/main/java/org/obiba/mica/micaConfig/MicaConfigService.java, mica-rest/src/main/java/org/obiba/mica/micaConfig/rest/AggregationsConfigResource.java, mica-search/src/main/java/org/obiba/mica/search/JoinQueryExecutor.java, mica-web-model/src/main/java/org/obiba/mica/web/model/Dtos.java, mica-web-model/src/main/java/org/obiba/mica/web/model/MicaConfigDtos.java, mica-web-model/src/main/protobuf/Mica.proto, mica-web-model/src/main/protobuf/MicaSearch.proto, mica-web-model/src/test/java/org/obiba/mica/web/model/DatasetDtosTest.java, mica-web-model/src/test/java/org/obiba/mica/web/model/StudyDtosTest.java, mica-webapp/src/main/conf/mica-aggregations.yml
* default aggregations are defined in a configuration file:  classpath:/mica-aggregations.yml
* added web resource to override defaults: GET|POST /config/aggregations
=> MK198 - return aggregations localized title in search response

mica-search/src/main/java/org/obiba/mica/dataset/search/rest/variable/PublishedDatasetVariablesSearchResource.java, mica-web-model/src/main/protobuf/MicaSearch.proto
added aggregations in coverage result used to get facets information (titles and terms) in coverage page
=> added aggregations in coverage result

mica-core/src/main/java/org/obiba/mica/core/service/GitService.java, mica-core/src/main/java/org/obiba/mica/study/ConstraintException.java, mica-core/src/main/java/org/obiba/mica/study/service/StudyService.java, mica-core/src/test/java/org/obiba/mica/study/StudyServiceTest.java, mica-rest/src/main/java/org/obiba/mica/study/rest/ConstraintExceptionMapper.java, mica-rest/src/main/java/org/obiba/mica/study/rest/DraftStudyResource.java, mica-web-model/src/test/java/org/obiba/mica/web/model/StudyDtosTest.java, mica-webapp/src/main/webapp/app/study/study-service.js, mica-webapp/src/main/webapp/app/study/views/study-list.html
MK-71 detect dependencies when deleting study
=> MK-71 detect dependencies when deleting study

mica-core/src/main/java/org/obiba/mica/file/TempFileService.java
remove tempfile document in mongodb when temp file is deleted
=> cleanup tempfile collection on delete

mica-core/src/main/java/org/obiba/mica/micaConfig/domain/OpalCredential.java
=> fix opal credential creation

mica-core/src/main/resources/ehcache.xml, mica-webapp/src/main/webapp/app/services.js
- and fixed mica webapp resource method to clear cache
=> ehcache changed to keep taxonomies in local heap

mica-core/src/main/java/org/obiba/mica/study/domain/Population.java
This reverts commit 326d9784c9a6f63a28cabad72bb7413e52efe55e.
=> Revert "bugfix-study-import - added more conditions to compareTo"

mica-core/src/main/java/org/obiba/mica/network/service/NetworkService.java, mica-core/src/main/java/org/obiba/mica/study/service/StudyService.java, mica-core/src/main/resources/ehcache.xml, mica-search/src/main/java/org/obiba/mica/search/AbstractPublishedDocumentService.java, mica-search/src/main/java/org/obiba/mica/search/JoinQueryExecutor.java, mica-search/src/main/java/org/obiba/mica/search/aggregations/AggregationMetaDataProvider.java, mica-search/src/main/java/org/obiba/mica/search/aggregations/AggregationMetaDataResolver.java, mica-search/src/main/java/org/obiba/mica/search/aggregations/DataCollectionEventAggregationMetaDataProvider.java, mica-search/src/main/java/org/obiba/mica/search/aggregations/DatasetAggregationMetaDataProvider.java, mica-search/src/main/java/org/obiba/mica/search/aggregations/DefaultAggregationMetaDataProvider.java, mica-search/src/main/java/org/obiba/mica/search/aggregations/NetworkAggregationMetaDataProvider.java, mica-search/src/main/java/org/obiba/mica/search/aggregations/StudyAggregationMetaDataProvider.java, mica-search/src/main/java/org/obiba/mica/search/aggregations/StudyTaxonomyMetaDataProvider.java, mica-search/src/main/java/org/obiba/mica/search/aggregations/TaxonomyAggregationMetaDataProvider.java, mica-search/src/main/java/org/obiba/mica/search/queries/AbstractDocumentQuery.java, mica-search/src/main/java/org/obiba/mica/search/queries/DatasetQuery.java, mica-search/src/main/java/org/obiba/mica/search/rest/EsQueryResultParser.java
cache for aggregations metadata providers
=> improvements in query performance

mica-core/src/main/java/org/obiba/mica/user/UserProfileService.java, mica-webapp/src/main/webapp/app/commons/localized/localized-service.js, mica-webapp/src/main/webapp/app/network/network-controller.js, mica-webapp/src/main/webapp/app/network/views/network-list.html, mica-webapp/src/main/webapp/i18n/en.json, mica-webapp/src/main/webapp/index.html
returned dummy subject in case Agate was down upon user profile request
=> MK-454 - implemented delete network with notification

mica-core/src/main/java/org/obiba/mica/core/domain/AbstractGitPersistable.java, mica-core/src/main/java/org/obiba/mica/core/repository/AttachmentStateRepository.java, mica-core/src/main/java/org/obiba/mica/core/upgrade/AttachmentsPathUpgrade.java, mica-core/src/main/java/org/obiba/mica/file/AttachmentState.java, mica-core/src/main/java/org/obiba/mica/file/FileService.java, mica-core/src/main/java/org/obiba/mica/file/impl/GridFsService.java, mica-core/src/main/java/org/obiba/mica/file/service/FileSystemService.java, mica-core/src/main/java/org/obiba/mica/file/service/TempFileService.java, mica-core/src/main/java/org/obiba/mica/study/StudyRepositoryImpl.java, mica-core/src/main/java/org/obiba/mica/study/domain/DataCollectionEvent.java, mica-core/src/main/java/org/obiba/mica/study/domain/Population.java, mica-core/src/main/java/org/obiba/mica/study/domain/Study.java, mica-core/src/main/java/org/obiba/mica/study/service/StudyService.java, mica-core/src/test/java/org/obiba/mica/study/StudyServiceTest.java, mica-rest/src/main/java/org/obiba/mica/file/rest/TempFileResource.java, mica-rest/src/main/java/org/obiba/mica/file/rest/TempFilesResource.java, mica-rest/src/main/java/org/obiba/mica/study/rest/DraftStudyResource.java, mica-rest/src/main/java/org/obiba/mica/study/rest/PublishedStudyResource.java, mica-rest/src/main/java/org/obiba/mica/study/service/StudyPackageImportServiceImpl.java, mica-web-model/src/main/java/org/obiba/mica/web/model/Dtos.java, mica-web-model/src/main/java/org/obiba/mica/web/model/PopulationDtos.java, mica-web-model/src/main/java/org/obiba/mica/web/model/StudyDtos.java, mica-web-model/src/test/java/org/obiba/mica/web/model/StudyDtosTest.java
Migration tasks still to be done.
=> MK-544 File system added, applied to study attachments

mica-search/pom.xml, pom.xml
=> Revert "Elasticsearch Groovy dependency removed"

mica-core/src/main/java/org/obiba/mica/file/service/FileSystemService.java, mica-core/src/main/java/org/obiba/mica/study/domain/Population.java, mica-webapp/src/main/webapp/app/contact/contact-controller.js, mica-webapp/src/main/webapp/app/network/network-controller.js, mica-webapp/src/main/webapp/app/study/study-controller.js
=> Various small fixes

mica-rest/src/main/java/org/obiba/mica/config/JerseyConfiguration.java, mica-rest/src/main/java/org/obiba/mica/micaConfig/rest/ConfigurationInterceptor.java, mica-rest/src/main/java/org/obiba/mica/web/rest/security/AuditInterceptor.java, mica-webapp/pom.xml, mica-webapp/src/main/conf/logback.xml, pom.xml
And Mica server version is added in response headers.
=> Rest calls are logged in a rest.log file (json format for logstash)

mica-core/src/main/java/org/obiba/mica/micaConfig/event/MicaConfigUpdatedEvent.java, mica-core/src/main/java/org/obiba/mica/micaConfig/service/MicaConfigService.java, mica-core/src/main/java/org/obiba/mica/network/domain/Network.java, mica-core/src/main/java/org/obiba/mica/network/service/NetworkService.java, mica-core/src/main/java/org/obiba/mica/study/domain/Study.java, mica-core/src/main/java/org/obiba/mica/study/service/StudyService.java, mica-core/src/test/java/org/obiba/mica/study/StudyServiceTest.java, mica-web-model/src/main/java/org/obiba/mica/web/model/MicaConfigDtos.java, mica-web-model/src/main/java/org/obiba/mica/web/model/NetworkDtos.java, mica-web-model/src/main/java/org/obiba/mica/web/model/PersonDtos.java, mica-web-model/src/main/java/org/obiba/mica/web/model/StudyDtos.java, mica-web-model/src/test/java/org/obiba/mica/web/model/StudyDtosTest.java, mica-webapp/src/main/webapp/app/config/config-controller.js, mica-webapp/src/main/webapp/app/config/views/config-view.html, mica-webapp/src/main/webapp/app/network/network-controller.js, mica-webapp/src/main/webapp/app/study/study-controller.js
when removing a role, all documents (studies/networks) are updated and persisted (a new revision is created).
=> MK-585 fix remove deleted roles from studies/networks/persons

mica-web-model/src/main/java/org/obiba/mica/web/model/NetworkDtos.java, mica-web-model/src/main/java/org/obiba/mica/web/model/NetworkSummaryDtos.java, mica-web-model/src/main/protobuf/Mica.proto, mica-webapp/src/main/webapp/app/network/network-controller.js, mica-webapp/src/main/webapp/app/network/views/network-modal-contacts.html, mica-webapp/src/main/webapp/app/network/views/network-view-details.html
+ study and network ids added in network summary.
=> MK-618 Search for affiliated members from associated networks

mica-search/src/main/java/org/obiba/mica/search/queries/EmptyQueryWrapper.java, mica-search/src/main/java/org/obiba/mica/search/queries/QueryWrapper.java, mica-search/src/main/java/org/obiba/mica/search/queries/protobuf/QueryDtoWrapper.java, mica-search/src/main/java/org/obiba/mica/search/queries/rql/RQLNode.java, mica-search/src/main/java/org/obiba/mica/search/queries/rql/RQLQueryWrapper.java, mica-search/src/test/java/org/obiba/mica/search/queries/rql/RQLQueryWrapperTest.java
=> More Rql functions supported

mica-core/src/main/resources/taxonomies/mica-study.yml, mica-core/src/main/resources/taxonomies/mica-taxonomy.yml
label changes.
also error on mica-study.yml
=> MK-825 - Change words designations in the search criteria

mica-webapp/src/main/webapp/app/app.js, mica-webapp/src/main/webapp/app/controllers.js, mica-webapp/src/main/webapp/app/services.js
refactored session creation in angular app
=> MK-851 invalid profile name displayed in menu

mica-webapp/src/main/resources/i18n/en.json, mica-webapp/src/main/resources/i18n/fr.json, mica-webapp/src/main/webapp/app/dataset/dataset-controller.js, mica-webapp/src/main/webapp/app/network/network-controller.js, mica-webapp/src/main/webapp/app/services.js, mica-webapp/src/main/webapp/app/study/study-controller.js, mica-webapp/src/main/webapp/app/views/unsaved-modal.html
prompt when user has unsaved changes for network, study and dataset (study and harmonization)
=> MK-817 - Display confirmation message when a user leave a changing page without saving

mica-core/src/main/resources/taxonomies/mica-study.yml, mica-core/src/main/resources/taxonomies/mica-taxonomy.yml, mica-core/src/main/resources/taxonomies/mica-variable.yml
changes in taxonomy description
=> MK-880 - Change taxonomy's definitions

mica-core/src/main/resources/taxonomies/mica-study.yml
=> MK-885 - Correct some wording errors in taxonomies' descriptions

mica-webapp/src/main/webapp/app/network/views/network-general-info-form.html
Added language suffix to website input names
=> MK-910 - The UI does not show that the website input is on error when it is invalid

mica-core/src/main/java/org/obiba/mica/access/service/DataAccessRequestUtilService.java
Remove the review next possible status from the conditionally approved state
=> MK-494 - For the conditionally approved state

mica-core/src/main/java/org/obiba/mica/security/realm/MicaAuthorizingRealm.java, mica-rest/src/main/java/org/obiba/mica/project/rest/DraftProjectResource.java, mica-web-model/src/main/java/org/obiba/mica/web/model/PermissionsDtos.java, mica-web-model/src/main/java/org/obiba/mica/web/model/ProjectDtos.java, mica-web-model/src/main/protobuf/Mica.proto, mica-webapp/src/main/webapp/app/project/views/project-list.html, mica-webapp/src/main/webapp/app/project/views/project-view.html
DAO have all permissions on any project.
=> MK-864 Project associated permissions

mica-core/src/main/java/org/obiba/mica/micaConfig/domain/DataAccessForm.java, mica-core/src/main/java/org/obiba/mica/micaConfig/domain/ProjectForm.java, mica-core/src/main/java/org/obiba/mica/security/service/SubjectAclService.java, mica-rest/src/main/java/org/obiba/mica/micaConfig/rest/DataAccessFormResource.java, mica-rest/src/main/java/org/obiba/mica/micaConfig/rest/DataAccessPermissionsConfigurationService.java, mica-rest/src/main/java/org/obiba/mica/micaConfig/rest/DataAccessResource.java, mica-rest/src/main/java/org/obiba/mica/micaConfig/rest/ProjectFormResource.java, mica-web-model/src/main/java/org/obiba/mica/web/model/Dtos.java, mica-web-model/src/main/java/org/obiba/mica/web/model/MicaConfigDtos.java, mica-web-model/src/main/protobuf/Mica.proto, mica-webapp/src/main/resources/i18n/en.json, mica-webapp/src/main/resources/i18n/fr.json, mica-webapp/src/main/webapp/app/access-config/data-access-config-controller.js, mica-webapp/src/main/webapp/app/access-config/data-access-config-service.js, mica-webapp/src/main/webapp/app/access-config/views/data-access-config-form.html, mica-webapp/src/main/webapp/app/permission/permission-config-modal-form.html, mica-webapp/src/main/webapp/app/permission/permission-config-table-template.html, mica-webapp/src/main/webapp/app/permission/permission-directives.js, mica-webapp/src/main/webapp/app/project-config/project-config-controller.js, mica-webapp/src/main/webapp/app/project-config/views/project-config-form.html
Added option to add/remove permissions to a user/group for data access requests and projects.
=> MK-866 - Allow "Access Officer Committee" to view all data access requests

mica-webapp/src/main/webapp/app/study/views/population/population-view.html
This fix is for the 1.3.x branch.
=> MK-1010 - add population.numberOfParticipants.info in study's view

mica-core/src/main/java/org/obiba/mica/micaConfig/domain/DataAccessForm.java, mica-core/src/main/java/org/obiba/mica/micaConfig/service/DataAccessFormService.java, mica-core/src/main/java/org/obiba/mica/micaConfig/service/EntityConfigService.java, mica-core/src/main/java/org/obiba/mica/micaConfig/service/InvalidFormSchemaException.java, mica-core/src/main/java/org/obiba/mica/micaConfig/service/ProjectConfigService.java, mica-core/src/main/resources/config/data-access-form/export-csv-schema.json, mica-rest/pom.xml, mica-rest/src/main/java/org/obiba/mica/access/rest/CsvReportGenerator.java, mica-rest/src/main/java/org/obiba/mica/access/rest/DataAccessRequestsResource.java, mica-rest/src/test/java/org/obiba/mica/access/rest/CsvReportGeneratorTest.java, mica-web-model/src/main/java/org/obiba/mica/web/model/MicaConfigDtos.java, mica-web-model/src/main/protobuf/Mica.proto
- Store schema as json for data access request export
- Define default schema for export of data access request
- Generate export of data access request
=> Data access request export :

mica-webapp/src/main/webapp/app/study/study-controller.js
fixing only branch 1.3.x. This fix is not applicable to the master banch.
=> MK-1004 fixed race condition initializing radio buttons

mica-core/pom.xml, mica-core/src/main/java/org/obiba/mica/config/CacheConfiguration.java, mica-core/src/main/java/org/obiba/mica/config/SecurityConfiguration.java, mica-core/src/main/java/org/obiba/mica/core/service/AgateRestService.java, mica-core/src/main/java/org/obiba/mica/security/SecurityManagerFactory.java, mica-core/src/main/java/org/obiba/mica/security/event/SubjectAclUpdatedEvent.java, mica-core/src/main/resources/application.properties, mica-core/src/test/java/org/obiba/mica/study/StudyServiceTest.java, pom.xml
also updated shiro from 1.2.3-java8 to 1.2.6
=> mica update spring-boot 1.2.8 to 1.3.7

mica-web-model/src/main/java/org/obiba/mica/web/model/PopulationDtos.java
Reintroduce properties in model for current study seeds.
=> fix population and dce fromDtos for current seeds

mica-webapp/src/main/webapp/app/config/config-controller.js
firefox still has a problem loading the languages for the switcher.
=> MK-1213 - refresh when possible language list changes

mica-webapp/src/main/webapp/app/study/views/study-view-details.html
had to render all populations separately
=> MK-1239 - show all populations when printing

mica-core/src/main/java/org/obiba/mica/core/service/AbstractGitPersistableService.java
=> MLSTRM-441

mica-search/src/main/java/org/obiba/mica/taxonomy/TaxonomyIndexer.java, mica-search/src/main/java/org/obiba/mica/taxonomy/TaxonomyVocabularyIndexable.java
Use exact matching of taxonomyName instead of id starting with taxonomyName
=> Delete es data with highter precision.

mica-search/src/main/java/org/obiba/mica/search/CountStatsDtoBuilders.java, mica-web-model/src/main/protobuf/MicaSearch.proto, mica-webapp/src/main/resources/i18n/en.json, mica-webapp/src/main/resources/i18n/fr.json
Will only count studies with study dataset variables
=> MK-1163 - add number of studies with variable count in count stats

mica-core/src/main/java/org/obiba/mica/core/domain/Person.java, mica-core/src/main/java/org/obiba/mica/network/domain/Network.java, mica-core/src/main/java/org/obiba/mica/study/domain/BaseStudy.java, mica-core/src/main/java/org/obiba/mica/study/domain/Study.java
This does not affect current behavior.
=> MK-1359 Base study class added to prepare harmonization study

mica-rest/src/main/java/org/obiba/mica/taxonomy/rest/TaxonomiesResource.java, mica-search/src/main/java/org/obiba/mica/search/ElasticSearchIndexer.java
=> Don't double index taxonomies

mica-webapp/src/main/webapp/app/study/classes/ViewController.js
also added population, revision and contact management to harmonization study view
=> fix for jshint unused parameter error

mica-search/src/main/java/org/obiba/mica/search/queries/AbstractDocumentQuery.java
=> Revert "Reduce log quantity"

mica-search/src/main/java/org/obiba/mica/search/csvexport/generators/StudiesCsvReportGenerator.java, mica-web-model/src/main/java/org/obiba/mica/web/model/StudySummaryDtos.java, mica-web-model/src/main/protobuf/Mica.proto
extract methods design and number of participants object from the model for use in studySummaryDto
=> MK-1411 MK-1419

mica-core/src/main/java/org/obiba/mica/micaConfig/service/helper/AbstractIdAggregationMetaDataHelper.java, mica-core/src/main/java/org/obiba/mica/micaConfig/service/helper/AggregationMetaDataProvider.java, mica-core/src/main/java/org/obiba/mica/micaConfig/service/helper/DatasetIdAggregationMetaDataHelper.java, mica-core/src/main/java/org/obiba/mica/micaConfig/service/helper/DceIdAggregationMetaDataHelper.java, mica-core/src/main/java/org/obiba/mica/micaConfig/service/helper/NetworkIdAggregationMetaDataHelper.java, mica-core/src/main/java/org/obiba/mica/micaConfig/service/helper/StudyIdAggregationMetaDataHelper.java, mica-search/src/main/java/org/obiba/mica/dataset/search/rest/variable/CoverageByBucket.java, mica-search/src/main/java/org/obiba/mica/dataset/search/rest/variable/CoverageByBucketFactory.java, mica-search/src/main/java/org/obiba/mica/search/CoverageQueryExecutor.java, mica-search/src/main/java/org/obiba/mica/search/aggregations/AggregationMetaDataResolver.java, mica-search/src/main/java/org/obiba/mica/search/aggregations/ConfigurationTaxonomyMetaDataProvider.java, mica-search/src/main/java/org/obiba/mica/search/aggregations/DataCollectionEventAggregationMetaDataProvider.java, mica-search/src/main/java/org/obiba/mica/search/aggregations/DatasetAggregationMetaDataProvider.java, mica-search/src/main/java/org/obiba/mica/search/aggregations/DefaultAggregationMetaDataProvider.java, mica-search/src/main/java/org/obiba/mica/search/aggregations/NetworkAggregationMetaDataProvider.java, mica-search/src/main/java/org/obiba/mica/search/aggregations/StudyAggregationMetaDataProvider.java, mica-search/src/main/java/org/obiba/mica/search/aggregations/TaxonomyAggregationMetaDataProvider.java, mica-search/src/main/java/org/obiba/mica/search/queries/EsQueryResultParser.java, mica-web-model/src/main/protobuf/MicaSearch.proto
This allows to discriminate the buckets of different types.
=> MK-1366 Class name added to the bucket coverage result

mica-webapp/src/main/webapp/app/dataset/dataset-controller.js, mica-webapp/src/main/webapp/app/dataset/views/harmonization-study-tables-form.html
MK-1429 fix harmonization-dataset view revision fonctionality
=> MK-1427 - remove second call to /config/opal-projects

mica-core/src/main/resources/taxonomies/mica-variable.yml, mica-search/src/main/java/org/obiba/mica/dataset/search/VariableIndexConfiguration.java, mica-search/src/main/java/org/obiba/mica/search/CountStatsDtoBuilders.java
Also removed networkCountStatsDtoBuilder's useless networkId method argument.
=> clean code, removed variable networkId reference 

mica-webapp/src/main/webapp/app/commons/classes/ListController.js, mica-webapp/src/main/webapp/app/dataset/views/collection-dataset-list.html, mica-webapp/src/main/webapp/app/dataset/views/harmonization-dataset-list.html, mica-webapp/src/main/webapp/app/network/views/network-list.html, mica-webapp/src/main/webapp/app/project/views/project-list.html, mica-webapp/src/main/webapp/app/study/views/study-list.html
Use oldPageNumber parameter from directive instead of the scope value because, the scope value's changed before the callback.
=> MK-1510 - fix for list page paging directive

mica-search/src/main/java/org/obiba/mica/search/JoinQueryExecutor.java, mica-search/src/main/java/org/obiba/mica/search/queries/AbstractDocumentQuery.java, mica-search/src/main/java/org/obiba/mica/search/queries/DatasetQuery.java, mica-search/src/main/java/org/obiba/mica/search/queries/EmptyQueryWrapper.java, mica-search/src/main/java/org/obiba/mica/search/queries/EsQueryResultParser.java, mica-search/src/main/java/org/obiba/mica/search/queries/NetworkQuery.java, mica-search/src/main/java/org/obiba/mica/search/queries/QueryWrapper.java, mica-search/src/main/java/org/obiba/mica/search/queries/StudyQuery.java, mica-search/src/main/java/org/obiba/mica/search/queries/VariableQuery.java, mica-search/src/main/java/org/obiba/mica/search/queries/protobuf/QueryDtoWrapper.java, mica-search/src/main/java/org/obiba/mica/search/queries/rql/RQLNode.java, mica-search/src/main/java/org/obiba/mica/search/queries/rql/RQLQueryWrapper.java, mica-search/src/test/java/org/obiba/mica/search/queries/rql/RQLQueryWrapperTest.java, mica-search/src/test/java/org/obiba/mica/study/search/rest/AggregationYamlParserTest.java, mica-search/src/test/java/org/obiba/mica/study/search/rest/DtoParserTest.java, mica-search/src/test/java/org/obiba/mica/study/search/rest/QueryDtoHelperTest.java, mica-search/src/test/java/org/obiba/mica/support/TestElasticSearchClient.java, mica-web-model/src/main/protobuf/MicaSearch.proto
MK-1437 - removed default count in aggregation processing.
=> MK-1437 -Added source filtering and added RQL 'fields' operator.

mica-search/src/main/java/org/obiba/mica/dataset/search/AbstractEsDatasetService.java, mica-search/src/main/java/org/obiba/mica/dataset/search/EsDraftHarmonizationDatasetService.java, mica-search/src/main/java/org/obiba/mica/dataset/search/EsDraftStudyDatasetService.java, mica-search/src/main/java/org/obiba/mica/dataset/search/EsPublishedDatasetService.java, mica-search/src/main/java/org/obiba/mica/dataset/search/rest/AbstractPublishedDatasetResource.java, mica-search/src/main/java/org/obiba/mica/dataset/search/rest/AbstractPublishedDatasetsResource.java, mica-search/src/main/java/org/obiba/mica/dataset/search/rest/collection/PublishedStudyDatasetResource.java, mica-search/src/main/java/org/obiba/mica/file/search/EsDraftFileService.java, mica-search/src/main/java/org/obiba/mica/file/search/EsPublishedFileService.java, mica-search/src/main/java/org/obiba/mica/file/search/FileFilterHelper.java, mica-search/src/main/java/org/obiba/mica/network/search/EsDraftNetworkService.java, mica-search/src/main/java/org/obiba/mica/network/search/EsPublishedNetworkService.java, mica-search/src/main/java/org/obiba/mica/person/search/EsPersonService.java, mica-search/src/main/java/org/obiba/mica/project/search/EsDraftProjectService.java, mica-search/src/main/java/org/obiba/mica/project/search/EsPublishedProjectService.java, mica-search/src/main/java/org/obiba/mica/search/AbstractDocumentService.java, mica-search/src/main/java/org/obiba/mica/search/SearchEngineClient.java, mica-search/src/main/java/org/obiba/mica/search/queries/NetworkQuery.java, mica-search/src/main/java/org/obiba/mica/study/search/EsDraftStudyService.java, mica-search/src/main/java/org/obiba/mica/study/search/EsPublishedStudyService.java, mica-search/src/main/java/org/obiba/mica/taxonomy/EsTaxonomyTermService.java, mica-search/src/main/java/org/obiba/mica/taxonomy/EsTaxonomyVocabularyService.java, mica-search/src/main/java/org/obiba/mica/variable/search/EsPublishedDatasetVariableService.java, mica-spi/src/main/java/org/obiba/mica/spi/search/Searcher.java
Implemented in https://github.com/obiba/mica-search-es/commit/07be39ea6368fcf300728c661460cb0054d1b288
=> MK-1565 Various documents search methods added

mica-core/src/main/java/org/obiba/mica/core/upgrade/Mica310Upgrade.java
=> Revert "Technical/migration about displayed facets"

mica-webapp/src/main/resources/i18n/en.json, mica-webapp/src/main/resources/i18n/fr.json
Placeholder suggestion text add an example: Search by name or acronym
=> MLSTRM-487

mica-core/src/main/java/org/obiba/mica/core/domain/Comment.java, mica-core/src/main/java/org/obiba/mica/core/repository/CommentsRepository.java, mica-core/src/main/java/org/obiba/mica/core/service/CommentsService.java, mica-core/src/main/java/org/obiba/mica/web/model/CommentDtos.java, mica-rest/src/main/java/org/obiba/mica/access/rest/DataAccessRequestResource.java, mica-web-model/src/main/protobuf/Mica.proto, mica-webapp/src/main/resources/i18n/en.json, mica-webapp/src/main/resources/i18n/fr.json
=> First commit Private Comment

mica-core/pom.xml, pom.xml
https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#java-driver-compatibility
=> Mongodb driver 3.8.0

mica-core/src/main/java/org/obiba/mica/micaConfig/domain/MicaConfig.java, mica-core/src/main/java/org/obiba/mica/security/service/SubjectAclService.java, mica-core/src/main/java/org/obiba/mica/web/model/MicaConfigDtos.java, mica-search/src/main/java/org/obiba/mica/variable/search/rest/PublishedDatasetVariablesSetResource.java, mica-search/src/main/java/org/obiba/mica/variable/search/rest/PublishedDatasetVariablesSetsResource.java, mica-web-model/src/main/protobuf/Mica.proto, mica-webapp/src/main/webapp/app/config/views/config-form.html, mica-webapp/src/main/webapp/app/config/views/config-view.html
This fix may require a followup for better exceptions when managing carts.
=> Added validation managing cart/set; removed unnecessary cart/set configuration.

mica-core/src/main/java/org/obiba/mica/access/service/DataAccessRequestUtilService.java
=> Remove the submit button for admin when DAR is under review.

mica-rest/src/main/java/org/obiba/mica/access/rest/DataAccessAmendmentResource.java, mica-rest/src/main/java/org/obiba/mica/access/rest/DataAccessEntityResource.java, mica-rest/src/main/java/org/obiba/mica/access/rest/DataAccessRequestResource.java
Related to https://github.com/obiba/mica2/issues/3707
- id path param is set for all path resources
- pass the id to relevant methods
=> id path param in all resource methods

mica-core/src/main/resources/config/study-form/collection-definition.json, mica-core/src/main/resources/config/study-form/collection-schema.json
- Access section in study Form edition UI
=> QA 30/05/2019 Maelstrom fix:

mica-search/src/main/java/org/obiba/mica/search/AbstractIdentifiedDocumentService.java
https://github.com/obiba/mica2/issues/3725
https://github.com/obiba/mica2/issues/3716
=> Fix bugs :

mica-core/src/main/java/org/obiba/mica/access/service/DataAccessEntityService.java, mica-core/src/main/java/org/obiba/mica/micaConfig/domain/DataAccessForm.java, mica-core/src/main/java/org/obiba/mica/web/model/MicaConfigDtos.java, mica-web-model/src/main/protobuf/Mica.proto, mica-webapp/src/main/resources/i18n/en.json, mica-webapp/src/main/resources/i18n/fr.json, mica-webapp/src/main/webapp/app/access-config/views/data-access-config-form.html
=> Added config to allow/disallow DAR ID generation with leading zeros.

mica-webapp/src/main/webapp/app/config/views/config-form.html
=> translate groupte type names

mica-webapp/bower.json, mica-webapp/src/main/webapp/app/app.js, mica-webapp/src/main/webapp/app/study/classes/ViewController.js, mica-webapp/src/main/webapp/index.html
=> add angular ui-sortable dependencies

mica-webapp/bower.json, mica-webapp/src/main/webapp/app/app.js, mica-webapp/src/main/webapp/app/study/classes/ViewController.js, mica-webapp/src/main/webapp/index.html
Reverts obiba/mica2#3749 because CI fails
=> Revert "add angular ui-sortable dependencies"

mica-core/src/main/java/org/obiba/mica/core/repository/PersonAwareRepository.java
=> saving collection of distinct persons

mica-core/src/main/java/org/obiba/mica/core/repository/PersonAwareRepository.java
This reverts commit 38ee9b51988a0098ea6f5f9b4a7bd5b1f954c417.
=> Revert "saving collection of distinct persons (#3754)"

mica-core/src/main/java/org/obiba/mica/dataset/service/VariableSetService.java, mica-search/src/main/java/org/obiba/mica/variable/search/rest/PublishedDatasetVariablesSetResource.java, mica-webapp/package-lock.json
=> select idents for opal views

mica-webapp/src/main/webapp/app/commons/classes/ListController.js
=> escape unclosed quotes

mica-rest/src/main/java/org/obiba/mica/config/RestConfig.java, mica-webapp/src/main/conf/application-dev.yml
Make it possible to configure CORS Policy, this add to external Web Browser client to query the server
In addition it will be a step to update the Drupal7 to Drupal8
=>  CORS Config

mica-webapp/src/main/resources/i18n/en.json, mica-webapp/src/main/resources/i18n/fr.json
Add translation for Percentage of Studies
=> #3771 Study Design graph

mica-core/src/main/java/org/obiba/mica/core/upgrade/Mica372Upgrade.java, mica-core/src/main/resources/taxonomies/mica-study.yml, mica-webapp/src/main/resources/i18n/en.json, mica-webapp/src/main/resources/i18n/fr.json
Add translation
Update Stat year Ranges
=> Fix output improvement

mica-rest/src/main/java/org/obiba/mica/micaConfig/rest/MicaConfigResource.java, mica-webapp/src/main/webapp/app/config/config-service.js
=> Fixed 3814 by using QueryParam's for URLs.

mica-core/src/main/resources/config/data-access-form/schema.json, mica-core/src/main/resources/config/study-form/collection-schema.json
=> use pattern validation for website url field

mica-webapp/src/main/webapp/assets/libs/mica-query.js
Left the consoles for more QA on history
=> Fixed history.

mica-core/src/main/java/org/obiba/mica/study/service/AbstractStudyService.java, mica-rest/src/main/java/org/obiba/mica/study/rest/DraftHarmonizationStudyResource.java, mica-rest/src/main/java/org/obiba/mica/study/rest/DraftIndividualStudyResource.java, mica-webapp/src/main/resources/i18n/en.json, mica-webapp/src/main/resources/i18n/fr.json, mica-webapp/src/main/webapp/app/study/views/collection-study-view.html, mica-webapp/src/main/webapp/app/study/views/harmonization-study-view.html
=> add csv download resource for individual and harmonization studies

mica-core/src/main/java/org/obiba/mica/micaConfig/service/helper/OpalServiceHelper.java, mica-webapp/src/main/conf/application-dev.yml, mica-webapp/src/main/conf/application.yml
=> read application.yml to get default sort order

mica-webapp/src/main/webapp/assets/libs/mica-query.js
TODO: deleting terms in coverage needs more work when dealing with _exists_-like queries as the corresponding vocabulary is required to get the rest of the terms.
=> Added code to delete a query in coverage page

mica-webapp/src/main/webapp/app/commons/classes/ViewController.js, mica-webapp/src/main/webapp/app/study/classes/ViewController.js, mica-webapp/src/main/webapp/app/study/study-controller.js, mica-webapp/src/main/webapp/app/study/views/population/collection-population-view.html, mica-webapp/src/main/webapp/app/study/views/population/dce/data-collection-event-view.html
=> DCE can be viewed for revisions; DCE files can only be seen when study is in DRAFT mode

mica-core/src/main/java/org/obiba/mica/web/model/DatasetDtos.java, mica-core/src/main/java/org/obiba/mica/web/model/StudySummaryDtos.java
=> add only the specific population and dce in the summary

mica-core/src/main/java/org/obiba/mica/web/model/DatasetDtos.java, mica-core/src/main/java/org/obiba/mica/web/model/StudySummaryDtos.java
=> use dceUid

mica-webapp/src/main/webapp/app/project/project-service.js
=> deserialize content

mica-webapp/src/main/webapp/app/persons/persons-list.js, mica-webapp/src/main/webapp/app/persons/views/persons-list.html
=> Added page query param when listing persons.

mica-webapp/src/main/resources/_templates/admin.ftl, mica-webapp/src/main/webapp/app/admin/admin-router.js, mica-webapp/src/main/webapp/app/commons/components/pagination/size-selector/component.html, mica-webapp/src/main/webapp/app/commons/components/pagination/size-selector/component.js, mica-webapp/src/main/webapp/app/persons/person-view.js, mica-webapp/src/main/webapp/app/persons/persons-list.js, mica-webapp/src/main/webapp/app/persons/views/person-view.html, mica-webapp/src/main/webapp/app/persons/views/persons-list.html
=> Deep linked the page number and size.

mica-webapp/src/main/webapp/app/persons/persons-list.js
=> Fixed page size change and click on last page.

mica-webapp/src/main/webapp/app/commons/commons-service.js, mica-webapp/src/main/webapp/app/entity-statistics-summary/entity-statistics-summary-item.js, mica-webapp/src/main/webapp/app/entity-statistics-summary/entity-statistics-summary-view.js, mica-webapp/src/main/webapp/app/entity-statistics-summary/views/entity-statistics-summary-item.html
=> Added hyperlinks to the counts.

mica-webapp/src/main/webapp/app/commons/classes/ListController.js, mica-webapp/src/main/webapp/app/commons/commons-service.js, mica-webapp/src/main/webapp/app/persons/persons-list.js, mica-webapp/src/main/webapp/app/project/project-controller.js
=> Improved full-text search in listing pages of the Admin client. Prevent ES exceptions.

mica-webapp/src/main/webapp/app/entity-taxonomy-config/entity-taxonomy-config-service.js
=> Account for vocabularies of type keyword.

mica-webapp/src/main/webapp/app/network/views/network-view-details.html, mica-webapp/src/main/webapp/app/study/views/collection-study-view-details.html, mica-webapp/src/main/webapp/app/study/views/harmonization-study-view-details.html
=> Hid the Members related UI components in the revision section.

mica-rest/src/main/java/org/obiba/mica/micaConfig/rest/MicaConfigResource.java, mica-webapp/src/main/resources/i18n/en.json, mica-webapp/src/main/resources/i18n/fr.json, mica-webapp/src/main/webapp/app/entity-statistics-summary/entity-statistics-summary-view.js, mica-webapp/src/main/webapp/app/entity-statistics-summary/views/entity-statistics-summary-view.html
=> Accounted for more config settings when retrieving stats info.

mica-webapp/package-lock.json, mica-webapp/src/main/resources/_templates/models/network.ftl
=> Account for NULL values.

mica-core/src/main/java/org/obiba/mica/dataset/domain/DatasetVariable.java
=> Decode name only if the original token was encoded. 

mica-search/src/main/java/org/obiba/mica/variable/search/rest/PublishedDatasetVariablesSetsResource.java, mica-webapp/src/main/java/org/obiba/mica/web/controller/BaseController.java, mica-webapp/src/main/java/org/obiba/mica/web/controller/CartController.java, mica-webapp/src/main/java/org/obiba/mica/web/controller/domain/Cart.java, mica-webapp/src/main/java/org/obiba/mica/web/interceptor/SessionInterceptor.java, mica-webapp/src/main/resources/_templates/cart.ftl, mica-webapp/src/main/resources/_templates/dataset.ftl, mica-webapp/src/main/resources/_templates/index.ftl, mica-webapp/src/main/resources/_templates/libs/dataset-scripts.ftl, mica-webapp/src/main/resources/_templates/libs/navbar-menus-right.ftl, mica-webapp/src/main/resources/_templates/libs/network-scripts.ftl, mica-webapp/src/main/resources/_templates/libs/scripts.ftl, mica-webapp/src/main/resources/_templates/libs/settings.ftl, mica-webapp/src/main/resources/_templates/libs/study-scripts.ftl, mica-webapp/src/main/resources/_templates/libs/variable-scripts.ftl, mica-webapp/src/main/resources/_templates/variable.ftl, mica-webapp/src/main/resources/i18n/en.json, mica-webapp/src/main/resources/i18n/messages_en.properties, mica-webapp/src/main/resources/i18n/messages_fr.properties, mica-webapp/src/main/webapp/assets/css/obiba.css, mica-webapp/src/main/webapp/assets/js/mica.js
Next steps:
* list variables in the cart page, with all actions
* search page to handle `Mica_variable.sets` criterion
* search page to allow variables addition (not individually, for now)
=> Cart first commit, variables can be added from variable and dataset pages

mica-webapp/src/main/resources/i18n/en.json, mica-webapp/src/main/resources/i18n/fr.json, mica-webapp/src/main/webapp/app/config/config-controller.js, mica-webapp/src/main/webapp/app/config/views/config-form.html
=> Account for no result for graphics and more options needed for table rendering.

mica-webapp/src/main/webapp/assets/js/mica-search.js
tested with mica-taxonmy.yml
```
"name": "Mica_taxonomy"
"title":
"en": "Classifications"
"fr": "Classifications"
"description": {}
"keywords": {}
"license": "CC BY-NC 4.0"
"vocabularies":
- "name": "variable"
"title":
"en": "Variables"
"fr": "Variables"
"description":
"en": "Variables classifications."
"fr": "Classifications des variables."
"terms":
- "name": "Variable_chars"
"title":
"en": "Variables"
"fr": "Variables"
"description": {}
"terms":
- "name": "Mica_variable"
"title":
"en": "Properties"
"fr": "Propriétés"
"description":
"en": "Variable properties as defined in the catalogue."
"fr": "Propriétés des variables telles que définies dans le catalogue."
- "name": "something"
"title":
"en": "Group"
"terms":
- "name": "Mlstr_area"
"title":
"en": "Areas of Information"
"fr": "Aires …
```
=> manage multilevel taxonomy for target variable

mica-webapp/src/main/resources/_templates/libs/search-scripts.ftl, mica-webapp/src/main/resources/_templates/libs/search.ftl, mica-webapp/src/main/resources/_templates/libs/settings.ftl, mica-webapp/src/main/resources/_templates/models/search.ftl, mica-webapp/src/main/resources/_templates/search.ftl, mica-webapp/src/main/webapp/assets/js/mica-search.js
=> Created a list to filter and sort menu items

mica-search/src/main/java/org/obiba/mica/variable/search/rest/PublishedDatasetVariablesSetsResource.java, mica-webapp/src/main/resources/_templates/libs/search-scripts.ftl, mica-webapp/src/main/resources/_templates/libs/settings.ftl, mica-webapp/src/main/resources/_templates/search.ftl, mica-webapp/src/main/resources/i18n/messages_en.properties, mica-webapp/src/main/resources/i18n/messages_fr.properties, mica-webapp/src/main/webapp/assets/js/mica-search.js, mica-webapp/src/main/webapp/assets/js/mica.js
relates to #4058 
Variable set management page will follow.
=> button to add to set

mica-webapp/src/main/resources/_templates/datasets.ftl, mica-webapp/src/main/resources/_templates/libs/scripts.ftl, mica-webapp/src/main/resources/_templates/networks.ftl, mica-webapp/src/main/resources/_templates/projects.ftl, mica-webapp/src/main/resources/_templates/studies.ftl
=> Added tidy() function to normalize html text in document models.

mica-webapp/src/main/resources/_templates/cart.ftl, mica-webapp/src/main/resources/_templates/libs/document-set-scripts.ftl, mica-webapp/src/main/resources/_templates/libs/navbar-menus-right.ftl, mica-webapp/src/main/resources/_templates/libs/settings.ftl, mica-webapp/src/main/resources/_templates/list.ftl, mica-webapp/src/main/resources/_templates/search.ftl, mica-webapp/src/main/resources/i18n/messages_en.properties, mica-webapp/src/main/resources/i18n/messages_fr.properties, mica-webapp/src/main/webapp/assets/js/mica-search.js
relates to #4058 
improved:
- list's sidebar
- list items management 
- list creation
=> various improvements

mica-webapp/src/main/webapp/assets/js/mica-data-access.js, mica-webapp/src/main/webapp/assets/js/mica.js
=> Changed function-variable declarations by method declarations.

mica-webapp/src/main/webapp/assets/js/mica-query.js
=> Correct and resend limit query when totalHits is inferior to 'from'

mica-webapp/src/main/resources/_templates/datasets.ftl, mica-webapp/src/main/resources/_templates/libs/datasets.ftl, mica-webapp/src/main/resources/_templates/libs/networks.ftl, mica-webapp/src/main/resources/_templates/libs/settings.ftl, mica-webapp/src/main/resources/_templates/libs/studies.ftl, mica-webapp/src/main/resources/_templates/networks.ftl, mica-webapp/src/main/resources/_templates/studies.ftl
Various markup fixes and adjustments for non-MR sites.
=> List cards display

mica-rest/src/main/java/org/obiba/mica/web/rest/security/SessionsResource.java
=> Use username to set the Subject principal

mica-webapp/src/main/resources/_templates/admin.ftl, mica-webapp/src/main/resources/i18n/en.json, mica-webapp/src/main/resources/i18n/fr.json, mica-webapp/src/main/webapp/app/commons/components/person-institution-selector/component.js, mica-webapp/src/main/webapp/app/commons/components/person-institution-selector/institution-component.html, mica-webapp/src/main/webapp/app/commons/components/person-institution-selector/person-component.html, mica-webapp/src/main/webapp/app/contact/contact-controller.js, mica-webapp/src/main/webapp/app/contact/contact-modal-form.html
=> Implemented components to search persons and institutions.

mica-rest/src/main/java/org/obiba/mica/study/rest/StudiesImportResource.java
The list of members (contacts and investigators) was not being imported as expected.
=> Bug fix on the Studies Import (Members section)

mica-core/src/main/java/org/obiba/mica/network/service/NetworkService.java, mica-core/src/main/java/org/obiba/mica/study/service/AbstractStudyService.java
=> Removed unnecessary code.

mica-webapp/src/main/resources/_templates/search.ftl
=> css is now inlined in vue-mica-search

mica-webapp/Gruntfile.js, mica-webapp/package-lock.json, mica-webapp/package.json, mica-webapp/src/main/resources/_templates/libs/network-scripts.ftl, mica-webapp/src/main/resources/_templates/libs/search-scripts.ftl, mica-webapp/src/main/webapp/assets/js/mica-search.js, mica-webapp/src/main/webapp/assets/js/mica.js, mica-webapp/src/main/webapp/assets/js/vue-mica-search/builder.js, mica-webapp/src/main/webapp/assets/js/vue-mica-search/libs/criterion.js, mica-webapp/src/main/webapp/assets/js/vue-mica-search/libs/result-parsers.js, mica-webapp/src/main/webapp/assets/js/vue-mica-search/panel.js, mica-webapp/src/main/webapp/assets/js/vue-mica-search/result.js
=> integrate vue-mica-search library directly in mica

mica-webapp/src/main/java/org/obiba/mica/config/WebConfiguration.java
=> Added forbidden URLs filter

mica-webapp/src/main/java/org/obiba/mica/web/controller/DataAccessController.java, mica-webapp/src/main/java/org/obiba/mica/web/controller/domain/TimelineItem.java, mica-webapp/src/main/resources/_templates/models/data-access-comments.ftl
And also the DAO can delete the last comment (this feature was in the REST API but not available in the UI).
=> #4347 Form status change event added to the DAR's comments timeline

mica-search/src/main/java/org/obiba/mica/search/reports/DtosCsvReportGeneratorFactory.java, mica-search/src/main/java/org/obiba/mica/search/reports/generators/CsvReportGenerator.java, mica-search/src/main/java/org/obiba/mica/search/reports/generators/DatasetDtosCsvReportGenerator.java, mica-search/src/main/java/org/obiba/mica/search/reports/generators/DatasetVariableDtosCsvReportGenerator.java, mica-search/src/main/java/org/obiba/mica/search/reports/generators/NetworkDtosCsvReportGenerator.java, mica-search/src/main/java/org/obiba/mica/search/reports/generators/StudySummaryDtosCsvReportGenerator.java
=> use locale to try to get correct localized string when downloading csv

mica-core/src/main/java/org/obiba/mica/web/model/DatasetDtos.java, mica-web-model/src/main/protobuf/Mica.proto
first part of maelstrom-research/maelstrom-public-pages#165
=> add more info for the harmonied variables in the harmo table summary

mica-core/src/main/java/org/obiba/mica/file/FileStoreService.java, mica-core/src/main/java/org/obiba/mica/file/impl/GridFsService.java, mica-core/src/main/java/org/obiba/mica/file/service/FileSystemService.java
=> Added attachment ID to files so they can be isolated when deleting

mica-webapp/src/main/resources/_templates/signin.ftl
=> Fix - Password Field With Auto-Complete security improvement

mica-core/src/main/java/org/obiba/mica/access/service/DataAccessEntityService.java, mica-core/src/main/java/org/obiba/mica/core/support/IdentifierGenerator.java, mica-core/src/main/java/org/obiba/mica/micaConfig/domain/DataAccessConfig.java, mica-core/src/main/java/org/obiba/mica/web/model/MicaConfigDtos.java, mica-web-model/src/main/protobuf/Mica.proto, mica-webapp/src/main/resources/i18n/en.json, mica-webapp/src/main/resources/i18n/fr.json, mica-webapp/src/main/webapp/app/access-config/views/data-access-config-form.html
Default is still random id generation.
=> feat: data access identifiers can be generated incrementally #4434

mica-core/src/main/java/org/obiba/mica/study/service/IndividualStudyService.java
=> Invalidate cache before saving

mica-webapp/src/main/webapp/assets/js/mica-query.js
=> Make sure to update from correct target

mica-core/src/main/java/org/obiba/mica/access/export/DataAccessEntityExporter.java, mica-core/src/main/java/org/obiba/mica/micaConfig/service/AbstractDataAccessEntityFormService.java, mica-core/src/main/resources/config/data-access-agreement-form/export-word.json, mica-core/src/main/resources/config/data-access-amendment-form/export-word.json, mica-core/src/main/resources/config/data-access-feasibility-form/export-word.json, mica-core/src/main/resources/config/data-access-form/export-word.json, mica-core/src/main/resources/config/data-access-preliminary-form/export-word.json, mica-rest/src/main/java/org/obiba/mica/access/rest/DataAccessAgreementResource.java, mica-rest/src/main/java/org/obiba/mica/access/rest/DataAccessAmendmentResource.java, mica-rest/src/main/java/org/obiba/mica/access/rest/DataAccessFeasibilityResource.java, mica-rest/src/main/java/org/obiba/mica/access/rest/DataAccessPreliminaryResource.java, mica-rest/src/main/java/org/obiba/mica/access/rest/DataAccessRequestResource.java
=> feat: make word exports of data access requests configurable 

mica-webapp/src/main/resources/_templates/contact.ftl
=> Pass lang code to recaptcha
