- mica-core/src/main/java/org/obiba/mica/dataset/domain/Dataset.java
- mica-core/src/main/java/org/obiba/mica/network/domain/Network.java
- mica-core/src/main/java/org/obiba/mica/study/domain/DataCollectionEvent.java
- mica-core/src/main/java/org/obiba/mica/study/domain/Study.java
- mica-rest/src/main/java/org/obiba/mica/micaConfig/rest/MicaConfigResource.java
This pull request is focused on resolving occurrences of Sonar rule squid:MissingDeprecatedCheck - “ Deprecated elements should have both the annotation and the Javadoc tag ”. You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:MissingDeprecatedCheck
Please let me know if you have any questions.
Ayman Abdelghany.
>  Deprecated elements should have both the annotation and the Javadoc tag

- mica-core/src/main/java/org/obiba/mica/PdfUtils.java
- mica-core/src/main/java/org/obiba/mica/security/SubjectUtils.java
- mica-rest/src/test/java/org/obiba/mica/web/rest/TestUtil.java
- mica-search/src/main/java/org/obiba/mica/dataset/search/rest/harmonized/ContingencyUtils.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1118 - “Utility classes should not have public constructors ”. You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Please let me know if you have any questions.
Ayman Abdelghany.
>  Utility classes should not have public constructors

- mica-webapp/src/main/webapp/app/permission/permission-modal-form.html
In the edit permission form, disable the input for name and show title according to permission type
> MK-911 - Updating a draft's permission name/group should not be possible 

- mica-webapp/src/main/webapp/index.html
This would make the application fail if we don't use the di annotations (the square bracket with the name of the components to inject).
> use ngStrictDi to check for explicit dependency injection annotations

- mica-core/src/main/java/org/obiba/mica/micaConfig/event/TaxonomiesUpdatedEvent.java
- mica-core/src/main/java/org/obiba/mica/micaConfig/service/TaxonomyConfigService.java
- mica-search/src/main/java/org/obiba/mica/taxonomy/TaxonomyIndexer.java
- mica-webapp/src/main/webapp/app/entity-config/entity-config-controller.js
On the server side, when updating a taxonomy config (STUDY, NETWORK, DATASET [ and VARIABLE]), the taxonomy update event that is triggered will delete and index the taxonomies for the targeted taxonomy only.
The client will clear the angular session cache. 
This would affect the search page such that after an entity config update the taxonomy resource cache would be cleared thus an updated list of vocabularies would be shown for the search panel.
This will only affect mica2, not mica-drupal. For mica-drupal, unfortunatly, a page refresh would be required.
> MK-1181 - do a targeted re-index when saving a taxonomy config

- mica-core/src/main/java/org/obiba/mica/micaConfig/service/TaxonomyConfigService.java
- mica-search/src/main/java/org/obiba/mica/search/ElasticSearchIndexer.java
- mica-search/src/main/java/org/obiba/mica/taxonomy/TaxonomyIndexer.java
Removed events for indexing documents when taxonomy is updated. Indexing the documents would not be necessary at that stage because none of the documents would be using a newly created taxonomy or even if deleted (or renamed/moved), the taxonomy would not be found in the search.
Instead of calling delete index multiple times for each types (doing multiple searches), do the search once and do the delete request per type. The delete request is then added in a bulk request such that elastic search would be the one to manage those instead of mica.
> MK-1181 - use bulkRequest for delete

- mica-webapp/src/main/webapp/app/study/study-controller.js
Wrap timeline creation in a $timeout in order to simulate a DOM.ready event on angularjs' side.
Error was due to '#timeline' not existing when page was rendered.
> MK-1199 - no timeline when multiple dce on page refresh

- mica-webapp/src/main/conf/application-dev.yml
- mica-webapp/src/main/conf/application.yml
See [spring boot mongo documentation](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-nosql.html#boot-features-connecting-to-mongodb).
> Mongo setting is uri-based for compatibility with driver 3.x

- mica-webapp/src/main/webapp/app/controllers.js
- mica-webapp/src/main/webapp/index.html
This would ensure that translations would be configured for searches in a particular language.
> MK-1213 - only show confgured languages in the language switcher

- mica-webapp/src/main/webapp/app/controllers.js
also forced the scope digest by adding the promise in $scope.
> MK-1213 - use publicMicaConfigResource to get configured languages

- mica-webapp/src/main/resources/i18n/en.json
- mica-webapp/src/main/resources/i18n/fr.json
- mica-webapp/src/main/webapp/app/config/config-controller.js
- mica-webapp/src/main/webapp/app/config/views/config-roles-modal-form.html
- mica-webapp/src/main/webapp/app/network/views/network-view-details.html
- mica-webapp/src/main/webapp/app/study/views/study-view-details.html
Current keys with spaces and upper cases will still work. One only has to create the translation key exactly as the id was created.
> MK-1252 - add validator to role creation in config and translate role key in member buttons

- mica-webapp/src/main/resources/i18n/en.json
- mica-webapp/src/main/resources/i18n/fr.json
- mica-webapp/src/main/webapp/app/config/config-controller.js
- mica-webapp/src/main/webapp/app/network/views/network-view-details.html
- mica-webapp/src/main/webapp/app/study/views/study-view-details.html
Also modified the help text to inform of the prefix to add in the translation as well as a link to the translation page.
It should also be noted that old ids with spaces and upper cases will still work.
> MK-1251 - translate the default role ids

- mica-search/src/main/java/org/obiba/mica/file/search/EsPublishedFileService.java
ScopedProxyMode.INTERFACES uses jdk proxies targetting the beans interface types only while ScopedProxyMode.TARGET_CLASS would use CGLIB proxies targeting class AND interface types.
> use proxyMode TARGET_CLASS

- mica-search/src/main/java/org/obiba/mica/dataset/search/rest/harmonized/CsvHarmonizationVariablesWriter.java
The id could not be used when the table was a NetworkTable. Opted to use that fact and that of project and table being the same for resolver and table itself.
> MK-1212 - write csv data for networkTable

- mica-search/src/main/java/org/obiba/mica/search/queries/AbstractDocumentQuery.java
The variable query result would thus be sorted by datasetId then index and finally by the client defined sort (in our case it is by name). It would however be best if index was not set to "0" for all variables.
> MK-1162 - add datasetId and index sorts for a variable search query

- mica-search/src/main/java/org/obiba/mica/search/CountStatsDtoBuilders.java
- mica-search/src/main/java/org/obiba/mica/search/JoinQueryExecutor.java
A harmonizaed dataset is linked to one and only one harmonization study.
One observation is that the lists of harmonization and study tables are not at all reflected int the search.
> MK-1433 - fix datasetCountStats to be more inline with join query result hit counts

- mica-web-model/src/main/java/org/obiba/mica/web/model/DatasetDtos.java
- mica-web-model/src/main/java/org/obiba/mica/web/model/StudyDtos.java
Same is done for opal tables for a harmonized dataset.
> Bugfix - filter opal tables by access permission for a harmonization study detail

- mica-core/src/main/java/org/obiba/mica/dataset/domain/HarmonizationDataset.java
- mica-core/src/main/java/org/obiba/mica/dataset/service/HarmonizedDatasetService.java
- mica-core/src/main/java/org/obiba/mica/micaConfig/service/CacheService.java
- mica-core/src/main/java/org/obiba/mica/micaConfig/service/OpalService.java
- mica-core/src/main/java/org/obiba/mica/micaConfig/service/helper/OpalServiceHelper.java
- mica-core/src/main/java/org/obiba/mica/web/model/DocumentDigestDtos.java
- mica-rest/pom.xml
- mica-rest/src/main/java/org/obiba/mica/dataset/rest/PublishedDatasetsEntitiesResource.java
- mica-rest/src/main/java/org/obiba/mica/dataset/rest/harmonization/DraftDataschemaDatasetVariableResource.java
- mica-rest/src/main/java/org/obiba/mica/dataset/rest/harmonization/DraftHarmonizedDatasetResource.java
- mica-rest/src/main/java/org/obiba/mica/dataset/rest/rql/RQLCriteriaOpalConverter.java
- mica-rest/src/main/java/org/obiba/mica/dataset/rest/rql/RQLCriterionOpalConverter.java
- mica-rest/src/main/java/org/obiba/mica/dataset/rest/rql/RQLFieldReferences.java
- mica-search/src/main/java/org/obiba/mica/dataset/search/rest/AbstractPublishedDatasetResource.java
- mica-search/src/main/java/org/obiba/mica/dataset/search/rest/harmonization/CsvHarmonizationVariablesWriter.java
- mica-search/src/main/java/org/obiba/mica/dataset/search/rest/harmonization/PublishedDataschemaDatasetVariableResource.java
- mica-search/src/main/java/org/obiba/mica/dataset/search/rest/harmonization/PublishedHarmonizedDatasetVariableResource.java
- mica-web-model/src/main/protobuf/MicaSearch.proto
- pom.xml
This is a web service only and does not interfere with any of the other mica 3.1 features.
Example of query on command line: 
`mica rest -u administrator -p password -m GET "/datasets/entities/_count?query=range(fnac:PITUUS:Collected,(1.5,*)),in(fnac:SUKUP:Collected,(1))"`
> MK-1651 Entities count web service added for collected variables only

- mica-rest/src/main/java/org/obiba/mica/access/rest/CsvHistoryReportGenerator.java
- mica-search/src/main/java/org/obiba/mica/search/csvexport/CsvReportGenerator.java
- mica-search/src/main/java/org/obiba/mica/search/csvexport/GenericReportGenerator.java
- mica-search/src/main/java/org/obiba/mica/search/csvexport/generators/CsvReportGeneratorImpl.java
Will download csv in steps where steps will be dictated by client.
For now, standard csv download limits are hard-coded to a limit of 100000 except for carts where the limit is the configured "max items per set".
> rql download in steps

- mica-search/src/main/java/org/obiba/mica/search/queries/VariableQuery.java
This optimization basically reduces the Elasticsearch response by ~50% resulting in a quicker client response time. The UI rendering lag remains the same and it will be part of a future fix.
> Optimize coverage queries by excluding extra aggregations.

- mica-webapp/src/main/webapp/assets/js/mica-search.js
The `style="overflow-x: auto;` does not work 100%, the pager is always a little shifted to the left when scrolling is required. DataTable injects a parent `<div>` around `<table>` so the styling must be on this element as in PR.
> Added table-responsive to DT dom setting.

- mica-webapp/src/main/java/org/obiba/mica/web/controller/domain/Annotation.java
- mica-webapp/src/main/java/org/obiba/mica/web/controller/domain/HarmonizationAnnotations.java
Reverts obiba/mica2#4135
Because of this:
```
Caused by: freemarker.core.NonStringOrTemplateOutputException: For "${...}" content: Expected a string or something automatically convertible to string (number, date or boolean), or "template output" , but this has evaluated to an extended_hash (wrapper: f.t.SimpleHash):
==> harmoAnnotations.algorithmValue!""  [in template "variable.ftl" at line 248, column 65]
----
FTL stack trace ("~" means nesting-related):
- Failed at: ${harmoAnnotations.algorithmValue!""}  [in template "variable.ftl" at line 248, column 63]
```
> Revert "Return algorithm value as LocalizedString"

- pom.xml
Relates to #4159 
According to https://docs.mongodb.com/drivers/java/, 3.12 supports mongo up to 4.4 (note that `The 3.12 driver does not support all MongoDB 4.4 features`).
Drivers over 4.0 will incur breaking changes in mica. While 3.12 will only mark methods as deprecated.
A future update to 4+ will still be best.
> update mongo driver to 3.12

- mica-core/src/main/resources/config/data-access-amendment-form/definition.json
- mica-core/src/main/resources/config/data-access-form/definition.json
- mica-core/src/main/resources/config/data-access-preliminary-form/definition.json
There was a fix in ng-obiba-mica (c532bc4767e6d323da8c8fc1e0d4ff79ad2371da) to make word limits a range and consequently the type is not a string. Chose the range ("0:500") as default to hint the value can be a range, otherwise "500" also works.
> Use a string for wordLimit add-on

- mica-webapp/src/main/webapp/assets/css/bootstrap-3-4.css
Most probably due to css incompatibility the <input> , after editing, the Input had `width=1%` and `min-width=0`!!
The fix specifically target `bs-datepicker`. tested with default schema and CanPath's.
> Added a special css class for input
